"""users table

Revision ID: 565e1be2b6f1
Revises: 
Create Date: 2020-11-12 21:42:10.818264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '565e1be2b6f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_currency_code'), 'currency', ['code'], unique=True)
    op.create_index(op.f('ix_currency_name'), 'currency', ['name'], unique=True)
    op.create_index(op.f('ix_currency_payway'), 'currency', ['payway'], unique=True)
    op.alter_column('order', 'amount',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.create_index(op.f('ix_order_amount'), 'order', ['amount'], unique=False)
    op.create_index(op.f('ix_order_stime'), 'order', ['stime'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_order_stime'), table_name='order')
    op.drop_index(op.f('ix_order_amount'), table_name='order')
    op.alter_column('order', 'amount',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.drop_index(op.f('ix_currency_payway'), table_name='currency')
    op.drop_index(op.f('ix_currency_name'), table_name='currency')
    op.drop_index(op.f('ix_currency_code'), table_name='currency')
    # ### end Alembic commands ###
